import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "colidashboard",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className=" m-auto grid bg-gradient-to-r from-slate-900 to-slate-700 px-4 font-sans ">
        <main className=" text-white">{children}</main>
      </body>
    </html>
  );
}
